export const QUERY_KEY = {
  EMPLOYEE: {
    GET_LIST: 'GET_LIST_EMPLOYEE',
    GET_DETAIL: 'GET_DETAIL_EMPLOYEE',
    GET_DOCUMENTS: 'GET_EMPLOYEE_DOCUMENTS',
    GET_EVENTS: 'GET_EMPLOYEE_EVENTS'
  }
}
